[language-server.clangd--001]

command = "/run/current-system/sw/bin/clangd"

args = [

"--background-index",

"--compile-commands-dir=.",

]

[language-server.rust-analyzer]
command = "rust-analyzer"

[[language]]

auto-format = true

name = "cpp"

language-servers = ["clangd--001"] 

file-types = ["cc", "hh","hxx","h","cpp"]

[[language]]

auto-format = true

name = "c"

language-servers = [ "clangd--001"] 

file-types = ["c","h"]

[[language]]

auto-format = true

name = "rust"

file-types = ["rs"]

language-servers = ["rust-analyzer"]
