[language-server.clangd--001]

command = "/run/current-system/sw/bin/clangd"

args = [

"--background-index",

"--compile-commands-dir=.",

]

[[language]]

auto-format = true

name = "cpp"

language-servers = ["clangd--001"] 

file-types = ["cc", "hh","hxx"]

[[language]]

auto-format = true

name = "c"

language-servers = [ "clangd--001"] 

file-types = ["c","h"]
